# Tomcat
server.port: 1101
# Logging level (TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF)
logging:
    level:
        org.hibernate: WARN
        org.springframework: WARN
    file: githubApi.log
# Spring settings
spring:
    profiles.active: dev
    freemarker.cache: true
    resources.cache-period: 7200
    datasource:
        url: jdbc:mysql://localhost:3306/universityMemories?characterEncoding=utf8
        username: root
        password: root
    jpa:
        show-sql: false
        hibernate:
            # Hibernate DDL  auto: create, create-drop, update, validate
            ddl-auto: validate
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
            properties:
                hibernate.dialect: org.hibernate.dialect.MySQL5Dialect